### ISSUE TITLE
Ошибка при старте.

### ISSUE THREAD

**Issue by wergut** [abyss-soft/webpack-template-base#28]
Сделал все по инструкции. Но не пойму что пошло не так..
Помогите пожалуйста найти причину

./src/smart-gread-layer/smart-gread-layer.scss (./node_modules/mini-css-extract-plugin/dist/loader.js!./node_modules/css-loader/dist/cjs.js??ref--7-2!./node_modules/postcss-loader/src??ref--7-3!./node_modules/sass-loader/dist/cjs.js??ref--7-4!./src/smart-gread-layer/smart-gread-layer.scss)
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
Error: Node Sass version 7.0.0 is incompatible with ^4.0.0.
    at getSassImplementation (C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\sass-loader\dist\getSassImplementation.js:46:13)
    at Object.loader (C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\sass-loader\dist\index.js:40:61)
    at C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at runSyncOrAsync (C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\loader-runner\lib\LoaderRunner.js:143:3)
    at iterateNormalLoaders (C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at C:\Users\GOD\Documents\GitHub\webpack-template-base\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

**Comment by abyss-soft** [comment]
Ошибка возникла из-за вот этого:
`Node Sass version 7.0.0 is incompatible with ^4.0.0 || ^5.0.0 || ^6.0.0`

Обновил сборку, теперь все должно работать.
Склонируйте себе ее заново и запустите:

- git clone ...
- cd webpack-template-base
- npm install
